name=input("Enter Name: ")
fname=input("Enter Father's Name: ")
dob=str(input("Enter Date of Birth: "))
rollno=eval(input("Enter Roll Number: "))
sec=input("Enter Section: ")
perm=eval(input("Enter Percentage in Matriculation: "))
peri=eval(input("Enter Percentage in Intermediate: "))
gm=input("Grade in Matriculation: ")
gi=input("Grade in Intermediate: ")
print()
print("\tBIO DATA")
print("Name: ",name)
print("Father;s Name: ",fname)
print("Date of Birth: ",dob)
print("Roll Number: ",rollno)
print("Section: ",sec)
print("Percentage in Matriculation: ",perm,"%")
print("Percentage in Intermediate: ",peri,"%")
print("Grade in Matriculation: ",gm)
print("Grade in Intermediate: ",gi)