print("\t\t\t\t----- CV -----")
print()
print("\t\t\tPersonal Information")
print()
print("Name:\t\t\t\tAbdul Ahad")
print("Father's Name:\t\t\tAjaz Ahmed")
print("Contct Number:\t\t\t03432399400")
print("Email:\t\t\t\tabdul.ahad133@yahoo.com")
print("Address:\t\t\tR-219 Sector11C2, North Karachi")
print()
print("\t\t\tQualification")
print()
print("BS in Software Engineering\tSSUET\t\t\t\t\t2020-Present")
print("Intermediate\t\t\tGovt. College Formen Nazimabad\t\t2017-19")
print("Matriculation\t\t\tOxford High School\t\t\t2004-17")