x1=eval(input("Enter Number x1: "))
x2=eval(input("Enter Number x2: "))
y1=eval(input("Enter Number y1: "))
y2=eval(input("Enter Number y2: "))
distance=(((x2-x1)**2)+((y2-y1)**2)**0.5)
print(distance)